### PR TITLE
Default disk-usage-stats telemetry indices

### PR DESCRIPTION
**Pull request by nik9000**
When I made the `disk-usage-stats` telemetry device in #1428 there
wasn't a way to use have it collect telemetry from the indices defined
in `track.json`. This adds such a way.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks! This is an awesome addition, thanks for spotting that it could be done that way!

Let's merge this today otherwise the nightlies won't measure anything.

**Comment by pquentin** [comment]
We hit https://github.com/elastic/rally/issues/1430.

@elasticmachine run tests please

**Comment by nik9000** [comment]
:+1:

I have maybe an hour before I have to go out for a bit. It looks like the failing test is the docker distribution trying to run the geonames track in test mode. I'll see if I can reproduce it. In the mean time I've merged master and will push that.

**Comment by nik9000** [comment]
Or maybe it's a known transient thing. OK then!

**Comment by nik9000** [comment]
If I don't merge this in the next hour and the tests look good feel tree to merge. I'll get it when I get back if not.

**Comment by nik9000** [comment]
Thanks for the merge @pquentin !

**Pull request merged**
