### PR TITLE
Upgrade Python client to 7.14.0

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we upgrade the Python client to 7.14.0.

Relates #1272

### CODE REVIEW

**Comment by sethmlarson** [comment]
The `NotElasticsearchError` is legitimate, caused by using the OSS distribution of Elasticsearch instead of the Basic/Elastic license. Added an additional `--car-params=docker_image:docker.elastic.co/elasticsearch/elasticsearch` fixed the problem locally for me, trying now on CI.

**Comment by sethmlarson** [comment]
jenkins test this please

**Comment by danielmitterdorfer** [comment]
Even after my latest changes in https://github.com/elastic/rally/pull/1304 (merge into this branch), we still have issues, e.g.:

```
esrally race --distribution-version=6.8.0 --test-mode --track=geonames --on-error=abort --car=defaults,basic-license --track-params="bulk_indexing_clients:1"
```

This requires investigation.

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by sethmlarson** [comment]
@elasticmachine test this please

**Comment by b-deam** [comment]
@dliappis / @ebadyano / @DJRickyB - whilst @danielmitterdorfer is out I ran some tests to verify whether the client version upgrade would introduce any obvious regressions in performance and so far there doesn't appear to be anything obvious (see  https://github.com/elastic/rally/issues/1272#issuecomment-905189529).

**Review by dliappis — APPROVED** [review]
Thanks for the thorough work to validate whether there are any performance changes introduced by this change.

LGTM

**Pull request merged**
