### PR TITLE
Surface ES startup errors to the Rally CLI console

### PR DESCRIPTION
**Pull request by DJRickyB**
It can be frustrating to troubleshoot why a Rally-managed Elasticsearch instance is not starting. Currently, we only log in the console the sub process's return code, with no further information. If you are intimately familiar with where installations go, and how to preserve them, you can troubleshoot this manually, but it would seem to be better to log the issue the first time rather than requiring a round of reproduction and a process of manually trying it yourself.

A straightforward reproduction of this issue is the following invocation, with a too small heap size:
```
% esrally race --track geonames --distribution-version 8.2.0 --runtime-jdk bundled --kill-running-processes --test-mode --car-params heap_size:1k     

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Race id is [8da62001-efd4-4456-a757-0bf89dffa51b]
[INFO] Preparing for race ...
[ERROR] Daemon startup failed with exit code [1]. STDERR:

	Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
	output:
	Error occurred during initialization of VM
	Too small maximum heap
	error:

		at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:114)
		at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:79)
		at org.elasticsearch.tools.launchers.MachineDependentHeap.determineHeapSettings(MachineDependentHeap.java:61)
		at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
		at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:87)


[ERROR] Cannot race. Command '['./bin/elasticsearch', '-d', '-p', './pid']' returned non-zero exit status 1.
	Traceback (most recent call last):
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/mechanic.py", line 590, in receiveMsg_StartNodes
    self.mechanic.start_engine()
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/mechanic.py", line 707, in start_engine
    self.nodes = self.launcher.start(self.node_configs)
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 134, in start
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 134, in <listcomp>
    return [self._start_node(node_configuration, node_count_on_host) for node_configuration in node_configurations]
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 164, in _start_node
    node_pid = self._start_process(binary_path, env)
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 221, in _start_process
    raise e
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 216, in _start_process
    ProcessLauncher._run_subprocess(command_line=" ".join(cmd), env=env)
  File "/Users/rick.boyd/dev/rally/esrally/mechanic/launcher.py", line 203, in _run_subprocess
    subprocess.run(
  File "/Users/rick.boyd/.pyenv/versions/3.8.10/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bin/elasticsearch', '-d', '-p', './pid']' returned non-zero exit status 1.


Getting further help:
*********************
* Check the log files in /Users/rick.boyd/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/latest/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /Users/rick.boyd/.rally/logs.

--------------------------------
[INFO] FAILURE (took 12 seconds)
--------------------------------
```

This change uses the `subprocess.run` function introduced in Python 3.5 to check the subprocess and print its output to the console on failure. There is some background to why we do not do this currently in #879, but I believe the output is worthwhile, and at the time I think 3.5 was very recently our minimum Python version so this option may have been overlooked... or there may be a more technical reason I am missing.

### CODE REVIEW

**Comment by DJRickyB** [comment]
Precipitating forum post: https://discuss.elastic.co/t/esrally-exceptions-launcherror-daemon-startup-failed-with-exit-code-1/302323/2

**Comment by pquentin** [comment]
I believe the build was interrupted after 80 minutes, which explains the failure. @dliappis Do you know how we can bump the timeout?

**Comment by dliappis** [comment]
> I believe the build was interrupted after 80 minutes, which explains the failure. @dliappis Do you know how we can bump the timeout?

As we don't have .ci definitions stored within this repo (see https://github.com/elastic/rally/pull/1395) unfortunately this is controlled in a different _private_ repo.

**Comment by pquentin** [comment]
> I've been looking at this the last couple hours and very consistently getting the timeout on this branch, I think the regression is legit

Would you still be interested in a review? I've been waiting for the investigation of that regression.

**Review by b-deam — APPROVED** [review]
Nice improvement, LGTM!

**Pull request merged**
