### PR TITLE
Use the new pip dependency resolver

### PR DESCRIPTION
**Pull request by hub-cap**
There is currently an issue with incompatible versions in our dependency
of aiohttp, which is causing installations to fail. Using the stricter
pip 2020 resolver, which is off by default in pip 20, fixes this
issue. The new resolver, which will be the new default in future pip
versions, is not ready for all use cases, but works fine for our use
case, so we are choosing to use it.

Relates https://discuss.python.org/t/announcement-pip-20-2-release/4863
Relates https://github.com/aio-libs/aiohttp/commit/2d36ef6911a1d49001381da40d658a70d64168fa
Relates https://github.com/aio-libs/aiohttp/issues/4987

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Comment by hub-cap** [comment]
Closing in favor of https://github.com/elastic/elasticsearch-py/pull/1401

**Comment by dliappis** [comment]
Based on an offline discussion, we think there's value having this rather than relying on the next released version based on https://github.com/elastic/elasticsearch-py/pull/1401, so I've reopened this.

**Review by sethmlarson — APPROVED** [review]

**Review by dliappis — APPROVED** [review]
LGTM

**Review by danielmitterdorfer — APPROVED** [review]
LGTM

**Pull request merged**
