### PR TITLE
Fix broken log archival/upload where there CI failures

### PR DESCRIPTION
**Pull request by dliappis**
Currently, CI failures for it tests fail immediately and prohibit
log archival/upload which makes understanding failures an impossible
task.

The approach taken here is an approach successfully taken in a different
repository.

### CODE REVIEW

**Comment by dliappis** [comment]
By the way, I've noticed that IT failures don't cause an immediately failure, at least in a localized environments e.g.

image

I'll look into this more, but I wonder if anyone has noticed anything similar so far?

**Review by michaelbaamonde — APPROVED** [review]
LGTM.

**Comment by michaelbaamonde** [comment]
> By the way, I've noticed that IT failures don't cause an immediately failure, at least in a localized environments e.g.

This is just how pytest works by default, AFAIK. You can have it abort on first failure ([see docs](https://docs.pytest.org/en/7.1.x/how-to/failures.html#stopping-after-the-first-or-n-failures)) but it'll run the full suite by default.

**Review by b-deam — APPROVED** [review]

**Comment by dliappis** [comment]
I tested this using a local jenkins workflow and it seems to fix the problem:

```
09:42:56 [Checks API] No suitable checks publisher found.
09:42:56 [Google Cloud Storage Plugin] Found 1 files to upload from pattern: .rally/$BUILD_NUMBER.tar.bz2
09:43:53 [Google Cloud Storage Plugin] Uploading: .rally/3.tar.bz2
09:43:57 Finished: FAILURE
```

**Pull request merged**
