### PR TITLE
Switch to native pytest in tests/track

### PR DESCRIPTION
**Pull request by pquentin**
I'm doing this folder by folder, the other example being https://github.com/elastic/rally/pull/1387. I've used unittest2pytest and reversed the yoga conditions as `assert a = 0` is invalid syntax. I find the result much clearer.

### CODE REVIEW

**Review by DJRickyB — APPROVED** [review]
LGTM. Scrolled through and checked general parity for lines-in/lines-out, and that unit tests pass.

Only thing to be sure of (that doesn't require a review volley) is that we're intentionally going with the more human/explicit/verbose
```
    assert x is True
```
vs just `assert x`

**Comment by pquentin** [comment]
> Only thing to be sure of (that doesn't require a review volley) is that we're intentionally going with the more human/explicit/verbose
> 
> ```
>     assert x is True
> ```
> 
> vs just `assert x`

I only did that in a series of nearly identical tests were a given value could be True, False or None. Since `assert x` works with truthy values and `assert not x` works with `False` I indeed preferred to be explicit in those tests. We even had a comment saying:

> Explicitly check in these tests for equality - assertFalse would also succeed if it is `None`.

I could have left it.

**Comment by pquentin** [comment]
However, in general there's no ambiguity and I do prefer the `assert x` form!

**Comment by pquentin** [comment]
Failed with: 

```
09:57:21 ____________________ test_docker_distribution[in-memory-it] ____________________
09:57:21 
09:57:21 cfg = 'in-memory-it'
09:57:21 
09:57:21     @it.random_rally_config
09:57:21     def test_docker_distribution(cfg):
09:57:21         port = 19200
09:57:21         # only test the most recent Docker distribution
09:57:21         dist = it.DISTRIBUTIONS[-1]
09:57:21         it.wait_until_port_is_free(port_number=port)
09:57:21 >       assert (
09:57:21             it.race(
09:57:21                 cfg,
09:57:21                 f'--pipeline="docker" --distribution-version="{dist}" '
09:57:21                 f'--track="geonames" --challenge="append-no-conflicts-index-only" --test-mode '
09:57:21                 f"--car=4gheap,basic-license --target-hosts=127.0.0.1:{port}",
09:57:21             )
09:57:21             == 0
09:57:21         )
09:57:21 E       assert 16384 == 0
09:57:21 E         +16384
09:57:21 E         -0
09:57:21 
09:57:21 it/distribution_test.py:53: AssertionError
09:57:21 - generated xml file: /var/lib/jenkins/workspace/elastic+rally+pull-request/junit-py38-it.xml -
```

@elasticmachine test this please

**Pull request merged**
