### PR TITLE
Update create track

### PR DESCRIPTION
**Pull request by gareth-ellis**
I seem to mess up my old branch - this is the same as PR #1836 
Add option to increase batch size when creating a track to speed up download of data. Update track layout to adhere to best practices

Creating tracks from large corpus can take quite a bit of time, so I have added the option to increase the batch size of scan, so if a user is running with a stable enough network connection and enough hardware resources on the rally instance, they can increase the batch size to speed up download.

I have also updated the track layout to better match how we tend to layout our tracks

There was feedback to add more docs, so that's done too

### CODE REVIEW

**Comment by ebadyano** [comment]
@gareth-ellis Thank you for updating the docs. LGTM.

One additional thing, since you are alreday updating the docs do you mind adding an option for data streams? During last review when I tested the change with datastreams I didn't realize I needed to specify `--data-streams` to actually make track create to include them in the track. See https://github.com/elastic/rally/pull/1531/files
I will test it shortly to confirm it works

**Comment by gareth-ellis** [comment]
The data-stream option is already in the docs - https://esrally.readthedocs.io/en/stable/command_line_reference.html#data-streams - or were you meaning something different?

**Comment by ebadyano** [comment]
> The data-stream option is already in the docs - https://esrally.readthedocs.io/en/stable/command_line_reference.html#data-streams - or were you meaning something different?

You are right, I somehow missed it.

**Comment by gareth-ellis** [comment]
I'd like to add the option to setup writing back to the datastream too - that isn't currently in place, but I thought that could be in a seperate PR

**Review by ebadyano — APPROVED** [review]
LGTM

**Pull request merged**
