### PR TITLE
Add CI for Python 3.9.0

### LINKED ISSUE #1074: Ensure Rally is compatible with Python 3.9
[Python 3.9 has been recently released](https://docs.python.org/release/3.9.0/whatsnew/3.9.html). At the moment Rally only supports Python 3.8 but we should add Python 3.9 to our CI test matrix and iron out any issues.

### PR DESCRIPTION
**Pull request by dliappis**
Closes #1074

### CODE REVIEW

**Comment by dliappis** [comment]
CI failed with:

```
python-build: definition not found: 3.9.0
14:45:16 
14:45:16 See all available versions with `pyenv install --list'.
14:45:16 
14:45:16 If the version you need is missing, try upgrading pyenv:
14:45:16 
14:45:16   cd /var/lib/jenkins/.pyenv/plugins/python-build/../.. && git pull && cd -
```

@hub-cap do you think it makes sense to have a similar ^^ Makefile target to pull the latest pyenv and reference it [here](https://github.com/elastic/rally/blob/f1f5d071cfd05c299d9ad9ac494ffa3dc5089661/.ci/build.sh#L43) rather than having to rely on rebuilding the CI golden image?

**Comment by hub-cap** [comment]
yes, I think we should control that instead of having infra control it, especially since we are the owners of upgrading our own python versions. Shall I do the needful here?

In this case would you like to have me get 3.9 installed in infra's image or use this as the test for doing the work ourselves?

**Comment by dliappis** [comment]
@elasticmachine please test this

**Comment by dliappis** [comment]
@elasticmachine test this please

**Comment by dliappis** [comment]
@elasticmachine test this please

**Comment by dliappis** [comment]
Depends on https://github.com/elastic/rally/pull/1096

**Comment by dliappis** [comment]
@elasticmachine test this please

**Review by hub-cap — APPROVED** [review]

**Pull request merged**
