### PR TITLE
Leave the host parsing on elasticsearch-py

### PR DESCRIPTION
**Pull request by HonzaKral**
That way you can specify 'https://user:secret@localhost:9200' if needed

There is already a comprehensive parsing logic in `elasticsearch-py` (0), no need to reimplement.

0 - https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L19-L59

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Thanks for PR! There is only one problem here: You can run Rally in different modes, e.g. against an existing cluster or you can have Rally setup the cluster for you (see [docs](http://esrally.readthedocs.io/en/latest/recipes.html#benchmarking-a-remote-cluster)). In the latter case, Rally will use the same command line parameter, iterate over the target hosts and contact a remote process on that host in order to tell it to spin up a node (see https://github.com/elastic/rally/blob/master/esrally/mechanic/mechanic.py#L141-L181). And for that we need the host/IP already in a separate field. While we could (theoretically) reuse the logic of elasticsearch-py in this component, it seems to me that this function is not meant to be used outside of elasticsearch-py (and rightly so IMHO).

So while I'd really love to get rid of this parsing logic, I fear it's not doable at the moment. Once we allow more complex multi-machine setups (with #71), we need to specify the cluster nodes differently anyway because maybe not every node that we need to setup can act as a coordinating node / client node. IMHO then would be the right time to merge this PR. 

I'd leave it open for now but mark it as "blocked" until #71 is resolved. Wdyt?

**Comment by HonzaKral** [comment]
I see no reason to avoid using the `_normalize_hosts` function from `elasticsearch-py`. It produces compatible output and is more robust in its parsing by using actual `urlparse` functionality. The linked code in `mechanic` can still work. The only change, if at all, might be to make sure no extra options are passed in to the `localhost` config. Like username/password etc which mechanic wouldn't know what to do with. That sounds like an easier fix while still allowing more functionality (would be happy to provide the additional code).

I do see your point though and it is a judgment call which means it's all up to you to decide what is more consistent with the rest of the project.

Thank you for your quick and thoughtful reply!

**Comment by danielmitterdorfer** [comment]
I was reluctant to use it as it's not part of the public API. But then let's do it this way.

> The only change, if at all, might be to make sure no extra options are passed in to the localhost config.

I think it's fine to just use the `hosts` dict as it's returned by `_normalize_hosts`. Could you just add the necessary change in `mechanic`? Then I think we're good to merge. :)

**Comment by HonzaKral** [comment]
I added a check in `mechanic` to verify that no advanced options were being passed in via the `hosts` settings. That should make this safe to merge, let me know if there is anything I have missed. Thanks!

**Pull request merged**
