### PR TITLE
Display ZGC collector stats in report

### PR DESCRIPTION
**Pull request by j-bennet**
Following up in https://github.com/elastic/rally/pull/1499.

This adds ZGC stats to the race report and comparison report.

I'm not very fond of all the hardcoded metric names, this can probably be improved.

Related PR: https://github.com/elastic/rally-teams/pull/74.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
This is great, thank you! Have you been able to run `scripts/analyze.py`? It fails here on something unrelated:

```
$ python scripts/analyze.py ~/.rally/benchmarks/races/da9e072b-ebe0-4380-817c-897901fb90d4/race.json
Traceback (most recent call last):
  File "scripts/analyze.py", line 269, in <module>
    main()
  File "scripts/analyze.py", line 265, in main
    plot(series, args.label)
  File "scripts/analyze.py", line 235, in plot
    plot_service_time(raw_data, label_key)
  File "scripts/analyze.py", line 89, in plot_service_time
    "percentiles": [decode_percentile_key(p) for p in service_time_metrics.keys()],
  File "scripts/analyze.py", line 89, in <listcomp>
    "percentiles": [decode_percentile_key(p) for p in service_time_metrics.keys()],
  File "scripts/analyze.py", line 58, in decode_percentile_key
    return float(k.replace("_", "."))
ValueError: could not convert string to float: 'mean'
```

Which is expected as it's not tested and the last real update was in October 2019.

**Comment by j-bennet** [comment]
@pquentin [this commit](https://github.com/elastic/rally/pull/1502/commits/32da26fef962adabb407bc6f9410b5774a3c6ab9) fixes the problem. I'm guessing the analyze script is not used much? Perhaps it should be deleted, instead of attempting to support it?

**Comment by pquentin** [comment]
> I'm guessing the analyze script is not used much? Perhaps it should be deleted, instead of attempting to support it?

Thanks for the suggestion! Discussed this internally and we agreed to remove analyze.py, done in https://github.com/elastic/rally/pull/1507. Can you please revert your last commit that introduces formatting changes and merge from master when #1507 is in?

Also, sorry that I forgot: can you please document those new values in docs/metrics.rst and docs/summary_report.rst? Search for `young_gen` in docs to find the relevant parts.

We're getting there!

**Comment by j-bennet** [comment]
> Can you please revert your last commit that introduces formatting changes

Oh man, I ran `black .` and that did it, and I didn't notice the extra files. So the codebase is not all "blackened"?

**Review by pquentin — CHANGES_REQUESTED** [review]
(Marking as "changes requested" for the docs)

**Review by pquentin — APPROVED** [review]
Thanks for iterating! LGTM.

**Pull request merged**
