### PR TITLE
Fix lint issue C0122

### PR DESCRIPTION
**Pull request by hub-cap**
Relates #838

### CODE REVIEW

**Comment by hub-cap** [comment]
@elasticmachine run tests please

**Comment by hub-cap** [comment]
please run tests already!

**Comment by hub-cap** [comment]
friends and enemies please test this

**Comment by danielmitterdorfer** [comment]
@hub-cap can you please add a `Relates #838` in your merge commit?

**Comment by hub-cap** [comment]
TIL: editing the first issue comment does *not* make its way into the commit msg. Sadly I did not get that added in the commit itself, but it is on this issue :/

**Pull request merged**
