### PR TITLE
Call the correct functions for `scroll-search` and `paginated-search` operations

### PR DESCRIPTION
**Pull request by michaelbaamonde**
In the course of getting started on https://github.com/elastic/rally/issues/1215, I discovered that `scroll-search` operations don't default to the index (or data stream) defined at the top level of the track under the `indices` key. The `pmc` and `geonames` tracks expose this. But if you explicitly provide an `index` parameter to the operation (as `http_logs` does)[^1] it works...

...by accident, it turns out. After digging into it, the core issue seems to be that there was no parameter source registered for `scroll-search` or `paginated-search` operations. So, neither the track object's `indices` attribute (necessary for choosing a default `index` parameter for the operation) nor the `operation-type` parameter (necessary for choosing the right function to call) was getting passed down the chain. But, the way the control flow works for dispatching to the appropriate function in the in the `Query.__call__` method, it wound up just issuing a request body query with a `pages` parameter, which happens to be the legacy implementation of scroll searches.

So, this commit addresses this by doing three things:

1. Augmenting `SearchParamSource` to pass the `operation-type` it receives through to its callers.
2. Registering `SearchParamSource` for both scrolls and paginated queries.
3. Enforcing `operation-type` as a mandatory paramater when calling the `Query` runner (necessary for custom parameter sources to avoid unexpected behavior.)

_That said_, I do wonder if it'd make sense to have separate classes (perhaps subclasses of `Query`) for each of these three operations. Their logic is distinct, it's possible that they should have their own parameter sources, and dispatching on the operation type within one large `__call__` method feels a little indirect given that we already have a mechanism for explicitly registering runners on a per-operation basis. I worry there may be some other trappy behavior lurking in here somewhere, but I opted to fix the bug within the current implementation instead of doing a larger refactoring along those lines. Happy to hear any thoughts on that front.

[^1]: https://github.com/michaelbaamonde/rally-tracks/commit/b700eac059ab42246768f44d0e656caf144a0269 contains the relevant changes that sparked this investigation.

### CODE REVIEW

**Comment by michaelbaamonde** [comment]
@elasticmachine test this please

**Comment by michaelbaamonde** [comment]
@danielmitterdorfer @DJRickyB The unrelated test failures are resolved now, so this is ready for another review. Thanks!

**Comment by DJRickyB** [comment]
thanks.  now that `operation-type` is not mandatory, can you undo changes to the tests here?

**Comment by michaelbaamonde** [comment]
> now that `operation-type` is not mandatory, can you undo changes to the tests here?

It's not mandatory in the sense that we don't require custom parameter sources to provide an operation type, but it is required that calls to the `Query` runner include one, somehow. The runner needs to have some awareness of the operation type in order to avoid the bug that motivated this PR initially.

That said, your comment did make me consider another problem, which is that defaulting to `search` as the operation type in the absence of a parameter source providing one means that custom parameter sources for `scroll-search` or `paginated-search` operations won't work as expected; they'll wind up ultimately calling the wrong function. So, this PR fixes the bug in the default case, but it's still lurking there for more advanced usage.

Ultimately, we really do rely on a 1:1 mapping between operation types and runners, and the registration mechanism provides a straightforward way to look up the exact runner for a given operation. The `Query` runner breaks this model in a way that forces us to _tell it_ what type of operation it needs to execute. Parameter sources give us a way to do that, but this is a bit of a hack on my part, and it entails a tighter coupling between parameter sources and runners than I think is intended.

With that said, I just pushed a commit that passes the `operation-type` to the runner by essentially injecting it into the params returned by the parameter source, but in a way that doesn't require any changes to the parameter source itself. This preserves the contract between parameter sources and runners, at least from the track author's perspective. It's another hack, though, which brings me back to:

> I worry there may be some other trappy behavior lurking in here somewhere, but I opted to fix the bug within the current implementation instead of doing a larger refactoring

I think it may be safer and quicker to refactor the `Query` runner into three separate classes instead of iterating further on workarounds. If this PR is mergeable after this latest commit, we can defer that, but if not, I think the time would be better spent on the more fundamental refactoring.

What do you think @DJRickyB @danielmitterdorfer?

**Comment by DJRickyB** [comment]
It's the end of my workday, I want to look at this deeper tomorrow, but I'll note that the "1:1" question came up in the course of #1190, when at the time it was deemed not necessary.  As far as I can tell you've bumped up against the limitations of that idea and I'm curious about @danielmitterdorfer's thoughts as well.

**Comment by danielmitterdorfer** [comment]
> I think it may be safer and quicker to refactor the Query runner into three separate classes instead of iterating further on workarounds. If this PR is mergeable after this latest commit, we can defer that, but if not, I think the time would be better spent on the more fundamental refactoring.

@michaelbaamonde and I had a chat on another channel about this. tl;dr as long as none of our tracks break with this change, we can go ahead and merge this and then start working on the refactoring in a separate PR immediately after.

**Comment by michaelbaamonde** [comment]
I ran all of our tracks and found no issues, so I'll merge.

**Pull request merged**
