### PR TITLE
Fix `make lint` on Python 3.10

### PR DESCRIPTION
**Pull request by pquentin**
In practice this means upgrading pylint which was failing on 3.9 and 3.10.

I would like to use Python 3.10 as my daily driver to avoid discovering issues like https://github.com/elastic/rally/issues/1484 only through our users, but I could not run `make lint` on Python 3.10 which made this impractical.

### CODE REVIEW

**Comment by michaelbaamonde** [comment]
The `precommit` [check failed](https://elasticsearch-ci.elastic.co/job/elastic+rally+pull-request+precommit/13/console) because the similarities checker found several violations of [`duplicate-code`](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/duplicate-code.html).

Do you want to disable this for now?

**Comment by pquentin** [comment]
For now I'm more concerned by the fact that I'm not seeing those errors locally! Do you see them when running `make lint`?

**Comment by dliappis** [comment]
> For now I'm more concerned by the fact that I'm not seeing those errors locally! Do you see them when running `make lint`?

I also don't see the above mentioned errors when I run this PR locally with a clean venv using `make lint` or `make precommit`.
I am using `Python 3.8.13`.

Kind of unrelated, `make install` reports:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hatchling 1.6.0 requires pluggy>=1.0.0, but you have pluggy 0.13.1 which is incompatible.
```

**Comment by pquentin** [comment]
I ended up just disabling that check like I've done in esbench as it's of low value anyway.

**Comment by pquentin** [comment]
> Kind of unrelated, `make install` reports:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> hatchling 1.6.0 requires pluggy>=1.0.0, but you have pluggy 0.13.1 which is incompatible.
> ```

Thanks! I opened https://github.com/elastic/rally/pull/1567 to address this.

**Review by michaelbaamonde — APPROVED** [review]
LGTM

**Pull request merged**
