### PR TITLE
Add an asyncio-based load generator

### LINKED ISSUE #852: An actorless load generator
At the moment Rally uses a process per client model (see https://github.com/elastic/rally/issues/9#issuecomment-179312337, https://github.com/elastic/rally/issues/58 and https://github.com/elastic/rally/commit/fe5dba3205c7c09a1491f349c6d4db19d89d2f9d for more details) and implements this with an actor system that allows clients (actors) to communicate with each other. The basic structure is that there is a controller actor (called `Driver`) for all clients and each client (actor) is responsible to execute scheduled tasks. However, this has several drawbacks that we've seen in practice:

* Complexity added by the actor framework: we need to spin up a separate process to communicate across nodes. Having the ability to communicate across nodes was mostly needed to spin up a cluster from the coordinator machine (where the benchmark has been started) but is less important for the load generator (although we also use it to distribute it across several machines). This was convenient in the early days but nowadays we let other tools handle remote connections during setup (e.g. Ansible) and [use Rally only to setup the individual nodes](https://github.com/elastic/rally/issues/697). Thus we don't need an actor system as much as we did before.
* Terminal output issues (the actor system performs a double-fork and thus we cannot write to the terminal)
* Issues to even startup the system on Windows that are hard to debug.
* Limit on the upper bound of supported clients (the whole system is just hanging if there are too many actors).
* Logging issues: logs are sent to a central component which then writes to the log file. If one actor issues too many logs, the actor system just becomes unresponsive (which is quite hard to debug because there are no logs to begin with).
* Debugging actor issues is quite tricky and we don't have much influence over what is logged.

Note that these limitations are due to the specific actor system implementation, and not necessarily conceptual issues. There are, however, also shortcomings that can be related to the process per client model:

* There is no built-in mechanism for clients to share state (this is not technically impossible, it's just a bit harder than with a single process model). Sharing state can be sometimes convenient e.g. if in an initial step, data is retrieved from Elasticsearch and then we can use this information in later steps. This is done for example by the eventdata track that retrieves the minimum and maximum date of log entries in Elasticsearch and uses it to choose appropriate date range parameters for simulating dashboard queries in later steps.
* Starting a process for each client is quite heavy-weight and thus it's not feasible to simulate thousands of clients with Rally.

We should explore a few options based on these shortcomings:

* Using the [Python Elasticsearch async client](https://github.com/elastic/elasticsearch-py-async).
* Using [asyncio](https://docs.python.org/3.8/library/asyncio.html) directly
* Keeping the process per client model but instead use [multiprocessing](https://docs.python.org/3.8/library/multiprocessing.html)

There are maybe other options as well but these are the choices that first come to mind. We should also refine this ticket as we proceed with our analysis.

IMHO it is ok to support only one load generator machine in the first step but we should aim to support the Rally tracks that we currently maintain.

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we add a new experimental subcommand `race-aync` to Rally. It
allows to specify significantly more clients than the current `race` subcommand.
The reason for this is that under the hood, `race-async` uses `asyncio` and runs
all clients in a single event loop. Contrary to that, `race` uses an actor
system under the hood and maps each client to one process.

As the new subcommand is very experimental and not yet meant to be used broadly,
there is no accompanying user documentation in this PR. Instead, we plan to
build on top of this PR and expand the load generator to take advantage of
multiple cores before we consider this usable in production (it will likely keep
its experimental status though).

In this PR we also implement a compatibility layer into the current load
generator so both work internally now with `asyncio`. Consequently, we have
already adapted all Rally tracks with a backwards-compatibility layer (see
elastic/rally-tracks#97 and rally-eventdata-track#80).

Closes #852

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
Note to reviewers:

The new subcommand only supports benchmarking and requires to use the `install` / `start` / `stop` subcommands to manage the respective Elasticsearch nodes.

Here are some example invocations:

```
# benchmark a local cluster in test mode
esrally race-async --track=geonames --on-error=abort --target-host="127.0.0.1:29200" --test-mode

# benchmark a local cluster with security enabled
esrally race-async --track=geonames --client-options="use_ssl:true,verify_certs:false,basic_auth_user:'rally',basic_auth_password:'rally-password'" --on-error=abort --target-host="127.0.0.1:29200"
```

Note that also the current load generator has changed (internally).

**Comment by danielmitterdorfer** [comment]
The PR build (Python 3.7) just failed with:

```
08:18:36 2020-02-25 08:18:36,185 -not-actor-/PID:56312 esrally.rally ERROR A fatal error occurred while running subcommand [stop].
08:18:36 Traceback (most recent call last):
08:18:36   File "/var/lib/jenkins/workspace/elastic+rally+pull-request/.tox/py37/lib/python3.7/site-packages/esrally/rally.py", line 713, in dispatch_sub_command
08:18:36     mechanic.stop(cfg)
08:18:36   File "/var/lib/jenkins/workspace/elastic+rally+pull-request/.tox/py37/lib/python3.7/site-packages/esrally/mechanic/mechanic.py", line 131, in stop
08:18:36     node_launcher.stop(nodes, metrics_store)
08:18:36   File "/var/lib/jenkins/workspace/elastic+rally+pull-request/.tox/py37/lib/python3.7/site-packages/esrally/mechanic/launcher.py", line 91, in stop
08:18:36     telemetry.add_metadata_for_node(metrics_store, node.node_name, node.host_name)
08:18:36   File "/var/lib/jenkins/workspace/elastic+rally+pull-request/.tox/py37/lib/python3.7/site-packages/esrally/telemetry.py", line 882, in add_metadata_for_node
08:18:36     metrics_store.add_meta_info(metrics.MetaInfoScope.node, node_name, "os_name", sysstats.os_name())
08:18:36 AttributeError: 'NoneType' object has no attribute 'add_meta_info'
```

which is rather odd given that we actually have a guard that checks that before invoking the function:

https://github.com/elastic/rally/blob/8a2ebe8817243e225f0bff8b4911e226ad3b926d/esrally/mechanic/launcher.py#L230-L231

Stopping a node is also single-threaded so I'm a bit at a loss why the `metrics_store` reference should be `None` but I'm documenting this so we have a reference that this has happened in case we see this again.

@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
This uncovered indeed a real issue that only happens when we run against a Docker container against an in-memory metrics store. I have pushed https://github.com/elastic/rally/pull/918 to address this.

**Comment by dliappis** [comment]
Additional note to reviewers: on an existing Rally installation, before reviewing this PR it's advisable to delete your .venv and recreate with `make prereq && make install`

**Comment by dliappis** [comment]
While testing against an Elasticsearch launched with an increased write thread pool

```
thread_pool:
  write:
    size: 6
    queue_size: 10000
```

I invoked Rally using

`esrally race-async --track=http_logs --on-error=abort --target-host="127.0.0.1:39200" --challenge=append-no-conflicts-index-only --track-params="bulk_indexing_clients:500"`

and hit an error at around `3%`:

`[ERROR] Cannot race-async. ('Request returned an error. Error type: transport, Description:  ()', None)`

Looking at the logs there was a request timeout, so probably Rally did what it should given that `--on-error=abort` but the CLI output could be improved.

<details><summary>Rally stack trace</summary>

```
2020-02-27 09:50:28,123 -not-actor-/PID:197 elasticsearch WARNING POST http://127.0.0.1:39200/_bulk [status:N/A request:60.009s]
Traceback (most recent call last):
  File "/Users/dl/source/elastic/rally/esrally/async_connection.py", line 105, in perform_request
    response = yield from self.session.request(method, url, data=body, headers=headers)
  File "/Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dl/source/elastic/rally/esrally/async_connection.py", line 106, in perform_request
    raw_data = yield from response.text()
  File "/Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2020-02-27 09:50:28,128 -not-actor-/PID:197 esrally.driver.driver ERROR Could not execute schedule
Traceback (most recent call last):
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1143, in __call__
    total_ops, total_ops_unit, request_meta_data = await execute_single(runner, self.es, params, self.abort_on_error)
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1218, in execute_single
    raise exceptions.RallyAssertionError(msg)
esrally.exceptions.RallyAssertionError: ('Request returned an error. Error type: transport, Description:  ()', None)
2020-02-27 09:50:28,654 -not-actor-/PID:197 esrally.metrics INFO Closing metrics store.
2020-02-27 09:50:28,655 -not-actor-/PID:197 esrally.rally ERROR Cannot run subcommand [race-async].
Traceback (most recent call last):
  File "/Users/dl/source/elastic/rally/esrally/racecontrol.py", line 406, in run_async
    new_metrics = race_driver.run()
  File "/Users/dl/source/elastic/rally/esrally/driver/async_driver.py", line 210, in run
    loop.run_until_complete(benchmark_runner())
  File "/Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/dl/source/elastic/rally/esrally/driver/async_driver.py", line 251, in _run_benchmark
    _ = await asyncio.gather(*aws)
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1143, in __call__
    total_ops, total_ops_unit, request_meta_data = await execute_single(runner, self.es, params, self.abort_on_error)
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1218, in execute_single
    raise exceptions.RallyAssertionError(msg)
esrally.exceptions.RallyAssertionError: ('Request returned an error. Error type: transport, Description:  ()', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dl/source/elastic/rally/esrally/rally.py", line 718, in dispatch_sub_command
    racecontrol.run_async(cfg)
  File "/Users/dl/source/elastic/rally/esrally/racecontrol.py", line 412, in run_async
    raise exceptions.RallyError(str(e)).with_traceback(tb)
  File "/Users/dl/source/elastic/rally/esrally/racecontrol.py", line 406, in run_async
    new_metrics = race_driver.run()
  File "/Users/dl/source/elastic/rally/esrally/driver/async_driver.py", line 210, in run
    loop.run_until_complete(benchmark_runner())
  File "/Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/dl/source/elastic/rally/esrally/driver/async_driver.py", line 251, in _run_benchmark
    _ = await asyncio.gather(*aws)
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1143, in __call__
    total_ops, total_ops_unit, request_meta_data = await execute_single(runner, self.es, params, self.abort_on_error)
  File "/Users/dl/source/elastic/rally/esrally/driver/driver.py", line 1218, in execute_single
    raise exceptions.RallyAssertionError(msg)
esrally.exceptions.RallyError: ("('Request returned an error. Error type: transport, Description:  ()', None)", None)
2020-02-27 09:50:28,742 -not-actor-/PID:197 esrally.driver.async_driver ERROR Uncaught exception in event loop: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-5039' coro=<AsyncTransport.main_loop() running at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:149> wait_for=<Future finished exception=ServerDisconnectedError() created at /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py:418> cb=[<TaskWakeupMethWrapper object at 0x106f1b1c0>()] created at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:214>, 'source_traceback': [<FrameSummary file /Users/dl/source/elastic/rally/.venv/bin/esrally, line 11 in <module>>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 912 in main>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 718 in dispatch_sub_command>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/racecontrol.py, line 406 in run_async>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/async_driver.py, line 210 in run>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 595 in run_until_complete>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 563 in run_forever>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 1836 in _run_once>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py, line 81 in _run>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1143 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1180 in execute_single>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 193 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 241 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 452 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py, line 84 in _wrapped>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py, line 1478 in bulk>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py, line 214 in perform_request>]}
2020-02-27 09:50:28,746 -not-actor-/PID:197 esrally.driver.async_driver ERROR Uncaught exception in event loop: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-5041' coro=<AsyncTransport.main_loop() running at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:149> wait_for=<Future finished exception=ServerDisconnectedError() created at /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py:418> cb=[<TaskWakeupMethWrapper object at 0x105da0c40>()] created at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:214>, 'source_traceback': [<FrameSummary file /Users/dl/source/elastic/rally/.venv/bin/esrally, line 11 in <module>>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 912 in main>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 718 in dispatch_sub_command>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/racecontrol.py, line 406 in run_async>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/async_driver.py, line 210 in run>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 595 in run_until_complete>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 563 in run_forever>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 1836 in _run_once>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py, line 81 in _run>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1143 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1180 in execute_single>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 193 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 241 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 452 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py, line 84 in _wrapped>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py, line 1478 in bulk>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py, line 214 in perform_request>]}
2020-02-27 09:50:28,753 -not-actor-/PID:197 esrally.driver.async_driver ERROR Uncaught exception in event loop: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-5043' coro=<AsyncTransport.main_loop() running at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:149> wait_for=<Future finished exception=ServerDisconnectedError() created at /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py:418> cb=[<TaskWakeupMethWrapper object at 0x1068f1b50>()] created at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:214>, 'source_traceback': [<FrameSummary file /Users/dl/source/elastic/rally/.venv/bin/esrally, line 11 in <module>>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 912 in main>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 718 in dispatch_sub_command>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/racecontrol.py, line 406 in run_async>
, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/async_driver.py, line 210 in run>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 595 in run_until_complete>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 563 in run_forever>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 1836 in _run_once>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py, line 81 in _run>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1143 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1180 in execute_single>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 193 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 241 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 452 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py, line 84 in _wrapped>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py, line 1478 in bulk>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py, line 214 in perform_request>]}
2020-02-27 09:50:28,759 -not-actor-/PID:197 esrally.driver.async_driver ERROR Uncaught exception in event loop: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-5045' coro=<AsyncTransport.main_loop() running at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:149> wait_for=<Future finished exception=ServerDisconnectedError() created at /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py:418> cb=[<TaskWakeupMethWrapper object at 0x106561220>()] created at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:214>, 'source_traceback': [<FrameSummary file /Users/dl/source/elastic/rally/.venv/bin/esrally, line 11 in <module>>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 912 in main>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 718 in dispatch_sub_command>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/racecontrol.py, line 406 in run_async>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/async_driver.py, line 210 in run>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 595 in run_until_complete>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 563 in run_forever>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 1836 in _run_once>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py, line 81 in _run>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1143 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1180 in execute_single>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 193 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 241 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 452 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py, line 84 in _wrapped>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py, line 1478 in bulk>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py, line 214 in perform_request>]}
2020-02-27 09:50:28,765 -not-actor-/PID:197 esrally.driver.async_driver ERROR Uncaught exception in event loop: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-5047' coro=<AsyncTransport.main_loop() running at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:149> wait_for=<Future finished exception=ServerDisconnectedError() created at /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py:418> cb=[<TaskWakeupMethWrapper object at 0x106992b50>()] created at /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py:214>, 'source_traceback': [<FrameSummary file /Users/dl/source/elastic/rally/.venv/bin/esrally, line 11 in <module>>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 912 in main>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/rally.py, line 718 in dispatch_sub_command>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/racecontrol.py, line 406 in run_async>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/async_driver.py, line 210 in run>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 595 in run_until_complete>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 563 in run_forever>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py, line 1836 in _run_once>, <FrameSummary file /Users/dl/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py, line 81 in _run>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1143 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/driver.py, line 1180 in execute_single>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 193 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 241 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/esrally/driver/runner.py, line 452 in __call__>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py, line 84 in _wrapped>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py, line 1478 in bulk>, <FrameSummary file /Users/dl/source/elastic/rally/.venv/lib/python3.8/site-packages/elasticsearch_async/transport.py, line 214 in perform_request>]}
```
</details>

**Comment by danielmitterdorfer** [comment]
Thanks for your review and also finding the reporting issue with the network timeout. I dug and it turns out that when a `ConnectionTimeout` is raised by the client, the exception message is not helpful so I've implemented special handling for this case in https://github.com/elastic/rally/pull/916/commits/92bee31f7f3a2f3332c13f10034b0d847fbef354.

**Pull request merged**
